Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024

.idea/.gitignore, .idea/OZ-CSC-480-HCI-521-Fall-2024.iml, .idea/modules.xml, .idea/vcs.xml
=> Added folders

frontend/components/ui/card.jsx, frontend/components/ui/label.jsx, frontend/components/ui/select.jsx, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/TaskPage.jsx
1. Added login page
2. Moved taskbar
3. Added BrowserRouter
=> Added Login & Router + Moved Taskbar

README.md, backend/auth-service/pom.xml, backend/auth-service/src/main/java/LoginServlet.java, backend/auth-service/src/main/java/LogoutServlet.java, backend/auth-service/src/main/liberty/config/.gitignore, backend/auth-service/src/main/liberty/config/server.xml, backend/database-service/pom.xml, backend/database-service/src/main/liberty/config/server.xml, backend/pom.xml, frontend/.env, frontend/src/pages/Login.jsx, frontend/src/pages/TaskPage.jsx, frontend/vite.config.js
unfortunately, OpenLiberty is allergic to .env files, so (at least right now) both a .env and pom.xml are used for configuration
=> added ok configuration support

.github/ISSUE_TEMPLATE/bug_report.md, frontend/components/ui/checkbox.jsx, frontend/package-lock.json, frontend/package.json, frontend/src/pages/TaskPage.jsx
1. Works somewhat well
2. Need to implement backend connection in the future
3. Need to add function for checkbox
=> Added Task Details Page 

frontend/package-lock.json, frontend/package.json, frontend/src/pages/TaskPage.jsx
=> Fixed commit errors

.idea/.gitignore, .idea/OZ-CSC-480-HCI-521-Fall-2024.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/modules.xml, .idea/vcs.xml, frontend/src/pages/TaskPage.jsx
1. Temporary for now
2. Does not account for real inputs
=> Backend Connection: Post Added

frontend/src/pages/Login.jsx
- Fix login page UI
- Update OAuth button to reflect github instead of google
- Update password show/hide function to fix type error
=> Update login page

.idea/workspace.xml, frontend/src/App.jsx, frontend/src/pages/Registration.jsx
Fixed the line that was previously going through "or register with"  text. Additionally, resized the card component to make sure the all the registration information fits correctly.  Finally, changed the register with google to register with github to better represent what we are actually doing.
=> Update Registration Page.

.idea/workspace.xml, frontend/components/SidePanel.jsx, frontend/components/ui/sidebar.jsx, frontend/src/pages/TaskPage.jsx
=> Updated Task Creation

backend/database-service/src/main/java/rest/resource/ProjectResource.java, backend/database-service/src/main/java/rest/resource/TaskResource.java, backend/database-service/src/main/java/rest/resource/UserResource.java, backend/database/src/main/java/DAO/ProjectDAO.java, backend/database/src/main/java/dao/TaskDAO.java, backend/database/src/main/java/dao/UserDAO.java, backend/database/src/main/java/model/Project.java, backend/database/src/main/java/model/User.java
I added a project object. Each project has an ID(Auto-incremented), Name, and description
=> Added Projects table and Crud methods

.idea/workspace.xml, frontend/components/ProjectAccordion.jsx, frontend/src/App.jsx, frontend/src/pages/ProjectPage.jsx, frontend/src/pages/TaskPage.jsx, frontend/src/styles/dropdown.css
=> Filter Demo Complete

backend/database/src/main/java/dao/TaskDAO.java
fixes failed deletion and some other bugs
=> fix 'no suitable driver'

frontend/index.html, frontend/src/App.jsx, frontend/src/pages/CompletedPage.jsx, frontend/src/pages/ProjectPage.jsx, frontend/src/pages/RecentlyDeleted.jsx, frontend/src/pages/TaskPage.jsx
Backend does not completely work; ask engine to look into it.
Deleting a task refreshes the element as well
=> Added support for completion + Minor QOL Changes

frontend/src/pages/RecentlyDeleted.jsx, frontend/src/pages/TaskPage.jsx
Fix error where useEffect was causing constant fetch requests to /tasks and /projects. Error was preventing checkbox checking
=> Fix fetch request spamming error

frontend/components/TaskSidePanel.jsx, frontend/tailwind.config.js
- Make name and date fields required
- Change parent div to form element w/ onSubmit prevent default to prevent page reload
- Make addEditTask trigger from form submission instead of button click
- Add max length to name and description inputs
- Require caused "required not defined" error
- It was changed to an ES module import
=> Fix issue #110: (Task Names) and fix tailwind animate import

frontend/src/pages/Registration.jsx
- Fix password validation when first input is modified after filling out password confirmation
- Move password validation to reusable function
=> Fix Issue #108: Password validation

frontend/components/TaskColumns.jsx, frontend/components/TaskTable.jsx
- Fix task sorting by swapping from tanstack table's alphanumeric sorting function to [alphanumericCaseSensistive](https://tanstack.com/table/v8/docs/api/features/sorting)
- Noticed issue where table row had to be selected in order to check checkbox
- Modified checkbox to stop on click event propagation to parent table row
- Made checkbox slightly larger to improve accessibility/usability
=> Fix Issue #113: Task sorting and checkbox selection

frontend/components/TaskTable.jsx, frontend/src/pages/RecentlyDeleted.jsx, frontend/src/pages/TaskPage.jsx
Workaround: FetchTask() can't be accessed currently so I'm using window.location.reload()
=> Checkbox Functionality

frontend/components/PasswordInput.jsx
- Fix password input show/hide icon to have correct behavior
=> Fix Issue #141: Password Icon

backend/auth-service/src/main/java/rest/AuthResource.java, backend/database-service/src/main/java/rest/resource/TaskResource.java, backend/database/src/main/java/dao/ProjectDAO.java, backend/database/src/main/java/dao/TaskDAO.java, backend/database/src/main/java/dao/UserDAO.java, frontend/components/ProjectProvider.jsx, frontend/components/TaskSidePanel.jsx, frontend/lib/taskProjectUtils.js, frontend/package-lock.json, frontend/package.json, frontend/proxyPlugin.js, frontend/src/pages/ProjectPage.jsx, frontend/src/pages/RecentlyDeleted.jsx, frontend/src/pages/TaskPage.jsx
- **Decoupled somewhat TaskPage, ProjectPage, and RecentlyDeleted to just each use some components, rather than using the entirety of TaskPage and having to do messy context switching**
- added project trash endpoints to proxy
- fixed a small bug with project trashing in the backend
=> decouple task pages for code usablilty

frontend/components/TaskSidePanel.jsx
SelectedTask would run even if no task was selected causing reference error
=> Fixed SelectedTask Bug

frontend/components/TaskColumnsDeleted.jsx, frontend/src/pages/RecentlyDeleted.jsx
- Align table headers
- Modify text size and padding for 'Projects' header
- Add accessible column names for Recover and Delete buttons on both tables
=> Style Tables on Recently Deleted Page

frontend/components/Dialog.jsx, frontend/components/TaskSidePanel.jsx
- Remove redundant style classes on side bar
- Change 'Delete Task?' dialog text to match functionality
=> Miscellaneous GUI Style / Usability Updates
